spring:
  profiles:
    active: @activatedProperties@

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

management:
  health:
    diskSpace:
      enabled: false
    ping:
      enabled: false
  endpoint:
    health:
      show-details: always