spring:
  application:
    name: communication-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5442/communication_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5682
    username: admin
    password: password
rabbitmq:
  queue: communicationSchedulerQueue
  exchange: communicationExchange
  routingkey: communicationRoutingKey

server:
  port: 8005
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    br:
      com:
        ligabue: INFO